// Pure computational core for fixture-transport: a damped bouncing ball,
// integrated step by step. The 60 frames are generated by actually running
// this loop (P4) — never hand-authored.

export interface BallFrame {
  i: number;
  /** Ball position in a 100×100 viewbox. */
  x: number;
  y: number;
}

export const FRAME_COUNT = 60;

export function generateFrames(count: number = FRAME_COUNT): BallFrame[] {
  const frames: BallFrame[] = [];
  const dt = 0.1;
  const gravity = 60;
  const floor = 88; // ball radius below this touches the bottom
  let x = 8;
  let y = 20;
  let vx = 16;
  let vy = 0;
  for (let i = 0; i < count; i++) {
    frames.push({ i, x, y });
    vy += gravity * dt;
    x += vx * dt;
    y += vy * dt;
    if (y > floor) {
      y = floor - (y - floor);
      vy = -vy * 0.75; // damped bounce
    }
    if (x > 92) {
      x = 92 - (x - 92);
      vx = -vx;
    }
    if (x < 8) {
      x = 8 + (8 - x);
      vx = -vx;
    }
  }
  return frames;
}
